apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: index.docker.io/cage1016/gokit-istio-security-extauthz
      buildpacks:
        builder: "gcr.io/buildpacks/builder:v1"
        env:
          - GOOGLE_BUILDABLE=cmd/extauthz/main.go
        dependencies:
          paths:
            - internal/app/extauthz/*
            - cmd/extauthz/main.go
deploy:
  kubectl:
    manifests:
    - ./deployments/kubernetes-manifests/*.yaml