apiVersion: skaffold/v1
kind: Config
build:
  artifacts:          
    - image: docker.io/cage1016/gokit-istio-security-add
      custom:
        buildCommand: make dev_docker_add
        dependencies:
          paths:
            - cmd/add/main.go
            - internal/app/add
            - internal/pkg
    - image: docker.io/cage1016/gokit-istio-security-foo
      custom:
        buildCommand: make dev_docker_foo
        dependencies:
          paths:
            - cmd/foo/main.go
            - internal/app/foo
            - internal/pkg            
    - image: docker.io/cage1016/gokit-istio-security-authz
      custom:
        buildCommand: make dev_docker_authz
        dependencies:
          paths:
            - cmd/authz/main.go
            - internal/app/authz
            - internal/pkg
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:dev"
  local: {}
deploy:
  helm:
    flags:
      upgrade:
        - --install
    releases:
      - name: gokit-istio-security
        chartPath: ./deployments/helm/gokit-istio-security
        imageStrategy:
          helm: {}
        values:
          add.image: docker.io/cage1016/gokit-istio-security-add
          foo.image: docker.io/cage1016/gokit-istio-security-foo
          authz.image: docker.io/cage1016/gokit-istio-security-authz