apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: http-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ingress-http
spec:
  hosts:
    - "*"
  gateways:
    - http-gateway
  http:
    - match:
      - uri:
          prefix: /api/v1/add/
      rewrite:
        uri: /
      route:
        - destination:
            host: add
            port:
              number: 80
          headers:
            request:
              add:
                version: v1
    - match:
      - uri:
          prefix: /api/v1/foo/
      rewrite:
        uri: /
      route:
        - destination:
            host: foo
            port:
              number: 80
          headers:
            request:
              add:
                version: v1                
    - match:
      - uri:
          prefix: /api/v1/authz/
      rewrite:
        uri: /
      route:
        - destination:
            host: authz
            port:
              number: 80
          headers:
            request:
              add:
                version: v1
